### ISSUE TITLE
test fails after importing package depending on markdown preview

### ISSUE THREAD

**Issue by wjureczka** [uiwjs/react-markdown-preview#198]
Hey! Thanks for your work on this! Awesome libraries.

I have strange behaviour that I can not fix.

I have two packages: package A, and package B.

Packages A contains a component that uses a markdown-preview. All tests in this package work. 
After importing the component from package A into package B, all tests in package B fail with error message:
```
  ● Test suite failed to run

    Jest encountered an unexpected token

    Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

    Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

    By default "node_modules" folder is ignored by transformers.

    Here's what you can do:
     • If you are trying to use ECMAScript Modules, see https://jestjs.io/docs/ecmascript-modules for how to enable it.
     • If you are trying to use TypeScript, see https://jestjs.io/docs/getting-started#using-typescript
     • To have some of your "node_modules" files transformed, you can specify a custom "transformIgnorePatterns" in your config.
     • If you need a custom transformation specify a "transform" option in your config.
     • If you simply want to mock your non-JS modules (e.g. binary assets) you can stub them out with the "moduleNameMapper" config option.

    You'll find more details and examples of these config options in the docs:
    https://jestjs.io/docs/configuration
    For information about custom transformations, see:
    https://jestjs.io/docs/code-transformation

    Details:

    /Users/Projects/___/node_modules/react-markdown/index.js:5
    export { uriTransformer } from './lib/uri-transformer.js';
    ^^^^^^

    SyntaxError: Unexpected token 'export'

      at Runtime.createScriptFromCode (../../node_modules/jest-runtime/build/index.js:1728:14)
      at Object.<anonymous> (../../node_modules/@uiw/react-markdown-preview/src/index.tsx:2:1)

```

Can anyone help with the error or did anyone encounter similar?  The jest's configs in both of packages are the same.

Cheers.

**Comment by wjureczka** [comment]
answered myself:
https://stackoverflow.com/questions/72382316/jest-encountered-an-unexpected-token-react-markdown

**Comment by jaywcjlove** [comment]
@wjureczka 

https://github.com/uiwjs/react-markdown-preview/blob/d77b5f2852416e29653e434f775a75610cea9b7c/package.json#L48-L50
